# CASE 1
# WITH T1 AS (
#     SELECT PARENT_ID, COUNT(PARENT_ID) AS PI
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NOT NULL
#     GROUP BY PARENT_ID
# )

# SELECT ECOLI_DATA.ID, IFNULL(T1.PI, 0) AS CHILD_COUNT
# FROM ECOLI_DATA LEFT JOIN T1 ON ECOLI_DATA.ID = T1.PARENT_ID
# ORDER BY ID;

# CASE 2
SELECT E1.ID, COUNT(E2.ID) CHILD_COUNT
FROM ECOLI_DATA E1 LEFT JOIN ECOLI_DATA E2
ON E1.ID = E2.PARENT_ID
GROUP BY 1
ORDER BY 1;