# 11월 해당 기간에 대여 중인 차들 목록
WITH CRCRH AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE ('2022-11-01' BETWEEN START_DATE AND END_DATE OR '2022-11-30' BETWEEN START_DATE AND END_DATE)
    ORDER BY 1
),
CRCDP AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND DURATION_TYPE = '30일 이상'
)


SELECT * 
FROM (
    SELECT CAR_ID, 
    CAR_TYPE, 
    IF (
        CAR_TYPE = '세단', 
        ROUND(DAILY_FEE * 30 * (1 - (SELECT DISCOUNT_RATE FROM CRCDP WHERE CAR_TYPE = '세단') / 100)), 
        ROUND(DAILY_FEE * 30 * (1 - (SELECT DISCOUNT_RATE FROM CRCDP WHERE CAR_TYPE = 'SUV') / 100))
    ) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CRCRH) 
    AND (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
) AS CAR_WITH_FEE
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
;