SELECT FLAVOR
FROM 
(
    SELECT F.FLAVOR, SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF F FULL OUTER JOIN JULY J ON F.SHIPMENT_ID = J.SHIPMENT_ID
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER
)
GROUP BY FLAVOR
LIMIT 3;