SELECT MR.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'yyyy-mm-dd') AS REVIEW_DATE
FROM REST_REVIEW RR JOIN MEMBER_PROFILE MR ON RR.MEMBER_ID = MR.MEMBER_ID
WHERE MR.MEMBER_ID = (
    SELECT MEMBER_ID 
    FROM 
    (
        SELECT MEMBER_ID
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID 
        ORDER BY COUNT(*) DESC
    )
    WHERE ROWNUM = 1
)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;