SELECT UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    TO_CHAR(UGR.CREATED_DATE, 'YYYY-mm-dd') AS CREATED_DATE
FROM USED_GOODS_BOARD UGB, USED_GOODS_REPLY UGR
WHERE UGB.BOARD_ID = UGR.BOARD_ID AND UGB.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND LAST_DAY(TO_DATE('2022-10-01', 'YYYY-MM-DD'))
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC;