SELECT R.PRODUCT_ID, R.PRODUCT_NAME, (O.AMOUNT * R.PRICE) AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
    ) O 
JOIN FOOD_PRODUCT R ON O.PRODUCT_ID = R.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, R.PRODUCT_ID;