SELECT R.PRODUCT_ID, R.PRODUCT_NAME, (O.AMOUNT * R.PRICE) AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY') = '2022' AND TO_CHAR(PRODUCE_DATE, 'mm') = '05'
    GROUP BY PRODUCT_ID
    ) O 
JOIN FOOD_PRODUCT R ON O.PRODUCT_ID = R.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, R.PRODUCT_ID;