SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_TREE.ITEM_ID
    FROM ITEM_TREE RIGHT JOIN ITEM_INFO  ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
    WHERE PARENT_ITEM_ID IS NOT NULL AND ITEM_TREE.PARENT_ITEM_ID IN (
        SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE'
    )
)
ORDER BY ITEM_ID DESC;
